alias install="sudo apt-get install"
alias update="sudo apt-get update"
alias upgrade="sudo apt-get upgrade"
alias remove="sudo apt-get remove"
alias purge="sudo apt-get purge"
alias x="sudo halt -p"
alias proxyon="sudo mv /etc/apt/apt.conf.d/01proxy.bak /etc/apt/apt.conf.d/01proxy"
alias proxyoff="sudo mv /etc/apt/apt.conf.d/01proxy /etc/apt/apt.conf.d/01proxy.bak"
